name: PvPEvent
website: https://www.spigotmc.org/resources/pvpevent.97786/
version: '${project.version}'
main: xyz.dysaido.pvpevent.PvPEventLoader
load: POSTWORLD
author: Dysaido
softdepend: [PlaceholderAPI]
description: "${project.description}"

# Remove outdated alert
api-version: 1.13