name: PvPEvent
main: xyz.dysaido.pvpevent.PvPEventLoader

version: ${version}
author: Dysaido
load: POSTWORLD
softdepend: [PlaceholderAPI]

description: "Simple PvP event plugin."
website: https://www.spigotmc.org/resources/pvpevent.97786/

# Prevent Legacy Detect
api-version: 1.13