name: PvPEvent
website: https://www.spigotmc.org/resources/pvpevent.97786/
version: '${project.version}'
main: xyz.dysaido.pvpevent.PvPEvent
load: STARTUP
authors: [ Dysaido ]
description: This is a game plugin for your server. You can make some arena and in those the players play an 1v1 game.
